remote_theme: dbaynard/daktilo

title: David Baynard
author:
  fullname: David Baynard
  github: dbaynard
  twitter: dbaynard
  linkedin: david-baynard
  publickey: /publickey

license: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">David Baynard</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
