remote_theme: dbaynard/daktilo

title: David Baynard
author:
  fullname: David Baynard
  github: dbaynard
  twitter: dbaynard
  linkedin: david-baynard
  publickey: /publickey

license: |
  <p>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
      <i class="fab fa-creative-commons"></i>
      <i class="fab fa-creative-commons-by"></i>
      <i class="fab fa-creative-commons-sa"></i>
    </a>
  </p>
  <p>
    This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">David Baynard</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  </p>
