plugins:
- jekyll-remote-theme

remote_theme: dbaynard/daktilo

title: David Baynard
author:
  fullname: David Baynard
  github: dbaynard
  twitter: dbaynard
  linkedin: david-baynard
  publickey: /publickey

license: cc-by-sa

excerpt_separator: <!--more-->
permalink: pretty
